[package]
authors = ["Carsten KÃ¶nig <carstenkoenig92@gmail.com>"]
edition = "2018"
name = "proxy"
version = "0.1.0"
[dependencies]
chrono = "*"
clap = "*"
hyper-tls = "*"
lazy_static = "*"
regex = "*"
warp = "0.3"

[dependencies.tokio]
features = ["full"]
version = "1"
